# Generated by Django 5.2.6 on 2026-09-01 19:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dormcalendar', '0001_initial'),
        ('presence', '0001_initial'),
        ('rooms', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EveningCheckSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('open', 'Nyitva'), ('closed', 'Lezárva')], default='open', max_length=16)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.CharField(blank=True, max_length=255)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('floor', models.PositiveSmallIntegerField()),
                ('calendar_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evening_sessions', to='dormcalendar.calendarday')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-calendar_day__date', 'floor'],
            },
        ),
        migrations.CreateModel(
            name='EveningCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(blank=True, max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='presence.statustype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evening_results', to='students.studentprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='inspections.eveningchecksession')),
            ],
            options={
                'ordering': ['room_number', 'student__full_name'],
            },
        ),
        migrations.CreateModel(
            name='MorningMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('state', models.CharField(choices=[('open', 'Nyitva'), ('closed', 'Lezárva')], default='open', max_length=16)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='MorningSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('open', 'Nyitva'), ('closed', 'Lezárva')], default='open', max_length=16)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.CharField(blank=True, max_length=255)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('cutoff_at', models.DateTimeField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('calendar_day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='morning_snapshot', to='dormcalendar.calendarday')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='inspections.morningmonth')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-calendar_day__date'],
            },
        ),
        migrations.CreateModel(
            name='MorningSnapshotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_name', models.CharField(max_length=200)),
                ('room_number', models.CharField(blank=True, max_length=16)),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('school_class', models.CharField(blank=True, max_length=32)),
                ('group_name', models.CharField(blank=True, max_length=128)),
                ('evening_status_code', models.CharField(blank=True, max_length=32)),
                ('evening_status_label', models.CharField(blank=True, max_length=64)),
                ('cutoff_status_code', models.CharField(blank=True, max_length=32)),
                ('cutoff_status_label', models.CharField(blank=True, max_length=64)),
                ('calculated_result', models.CharField(choices=[('present', 'Bent aludt'), ('absent', 'Nem volt bent'), ('left_overnight', 'Éjszaka elment'), ('returned_late', 'Éjszaka érkezett'), ('unknown', 'Nem ellenőrzött')], default='unknown', max_length=16)),
                ('final_result', models.CharField(choices=[('present', 'Bent aludt'), ('absent', 'Nem volt bent'), ('left_overnight', 'Éjszaka elment'), ('returned_late', 'Éjszaka érkezett'), ('unknown', 'Nem ellenőrzött')], default='unknown', max_length=16)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.morningsnapshot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='morning_items', to='students.studentprofile')),
            ],
            options={
                'ordering': ['floor', 'room_number', 'student_name'],
            },
        ),
        migrations.CreateModel(
            name='RoomCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('problems', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='rooms.room')),
            ],
            options={
                'ordering': ['room__number'],
            },
        ),
        migrations.CreateModel(
            name='RoomCheckHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('previous_problems', models.TextField(blank=True)),
                ('previous_notes', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('room_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='inspections.roomcheck')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'room check history',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomCheckSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('open', 'Nyitva'), ('closed', 'Lezárva')], default='open', max_length=16)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.CharField(blank=True, max_length=255)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('floor', models.PositiveSmallIntegerField()),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'floor'],
            },
        ),
        migrations.AddField(
            model_name='roomcheck',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='inspections.roomchecksession'),
        ),
        migrations.CreateModel(
            name='RoomCheckStudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presence_result', models.CharField(choices=[('present', 'Jelen'), ('absent', 'Nincs jelen'), ('unknown', 'Nem ellenőrzött')], default='unknown', max_length=16)),
                ('detail_code', models.CharField(blank=True, max_length=32)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('detail_note', models.CharField(blank=True, max_length=255)),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='inspections.roomcheck')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_check_results', to='students.studentprofile')),
            ],
            options={
                'ordering': ['student__full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='eveningchecksession',
            index=models.Index(fields=['state'], name='inspections_state_18bf18_idx'),
        ),
        migrations.AddConstraint(
            model_name='eveningchecksession',
            constraint=models.UniqueConstraint(fields=('calendar_day', 'floor'), name='eveningsession_unique_day_floor'),
        ),
        migrations.AddConstraint(
            model_name='eveningcheckresult',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='eveningresult_unique_session_student'),
        ),
        migrations.AddConstraint(
            model_name='morningmonth',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='morningmonth_unique_period'),
        ),
        migrations.AddConstraint(
            model_name='morningmonth',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='morningmonth_valid_month'),
        ),
        migrations.AddIndex(
            model_name='morningsnapshotitem',
            index=models.Index(fields=['snapshot', 'final_result'], name='inspections_snapsho_7a4b5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='morningsnapshotitem',
            constraint=models.UniqueConstraint(fields=('snapshot', 'student'), name='morningitem_unique_snapshot_student'),
        ),
        migrations.AddConstraint(
            model_name='roomchecksession',
            constraint=models.UniqueConstraint(fields=('date', 'floor'), name='roomchecksession_unique_day_floor'),
        ),
        migrations.AddConstraint(
            model_name='roomcheck',
            constraint=models.UniqueConstraint(fields=('session', 'room'), name='roomcheck_unique_session_room'),
        ),
        migrations.AddConstraint(
            model_name='roomcheck',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='roomcheck_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='roomcheckstudentresult',
            constraint=models.UniqueConstraint(fields=('room_check', 'student'), name='roomcheckstudent_unique_check_student'),
        ),
    ]
