# Generated by Django 5.2.6 on 2026-09-03 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
        ('presence', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morningmonth',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='morningsnapshot',
            name='month',
        ),
        migrations.RemoveField(
            model_name='morningsnapshot',
            name='calendar_day',
        ),
        migrations.RemoveField(
            model_name='morningsnapshot',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='morningsnapshot',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='morningsnapshot',
            name='locked_by',
        ),
        migrations.RemoveField(
            model_name='morningsnapshot',
            name='opened_by',
        ),
        migrations.RemoveField(
            model_name='morningsnapshot',
            name='reopened_by',
        ),
        migrations.RemoveField(
            model_name='morningsnapshotitem',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='morningsnapshotitem',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='morningsnapshotitem',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='roomcheckstudentresult',
            options={'ordering': ['room_number', 'student_name']},
        ),
        migrations.RemoveField(
            model_name='roomcheckstudentresult',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='roomcheckstudentresult',
            name='detail_code',
        ),
        migrations.RemoveField(
            model_name='roomcheckstudentresult',
            name='detail_note',
        ),
        migrations.RemoveField(
            model_name='roomcheckstudentresult',
            name='presence_result',
        ),
        migrations.AddField(
            model_name='roomcheckstudentresult',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='roomcheckstudentresult',
            name='room_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='roomcheckstudentresult',
            name='school_class',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='roomcheckstudentresult',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='presence.statustype'),
        ),
        migrations.AddField(
            model_name='roomcheckstudentresult',
            name='student_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='roomcheckstudentresult',
            index=models.Index(fields=['student', '-saved_at'], name='inspections_student_bef7a9_idx'),
        ),
        migrations.DeleteModel(
            name='MorningMonth',
        ),
        migrations.DeleteModel(
            name='MorningSnapshot',
        ),
        migrations.DeleteModel(
            name='MorningSnapshotItem',
        ),
    ]
