# Generated by Django 5.2.6 on 2026-09-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_remove_morningmonth_closed_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomcheckhistory',
            options={'ordering': ['-saved_at'], 'verbose_name': 'szobaellenőrzés előzmény', 'verbose_name_plural': 'szobaellenőrzés előzmények'},
        ),
        migrations.AlterField(
            model_name='roomcheck',
            name='notes',
            field=models.TextField(blank=True, verbose_name='megjegyzés'),
        ),
        migrations.AlterField(
            model_name='roomcheck',
            name='problems',
            field=models.TextField(blank=True, verbose_name='hibák'),
        ),
        migrations.AlterField(
            model_name='roomcheck',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='értékelés'),
        ),
    ]
