# Generated by Django 5.2.6 on 2026-09-01 19:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('empty', 'Nincs engedély'), ('active', 'Érvényes'), ('expired', 'Lejárt'), ('revoked', 'Visszavonva')], default='empty', max_length=16)),
                ('permission_type', models.CharField(blank=True, choices=[('standing', 'Állandó kimenő'), ('daily', 'Napi kimenő'), ('night', 'Éjszakai kimenő'), ('custom', 'Egyedi')], max_length=16)),
                ('value', models.CharField(blank=True, help_text='Free-form detail, e.g. times.', max_length=255)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_permission', to='students.studentprofile')),
            ],
            options={
                'ordering': ['student__full_name'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='leave_permi_status_0c9e28_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeavePermissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('grant', 'Kiadás'), ('update', 'Módosítás'), ('revoke', 'Visszavonás'), ('expire', 'Lejárat')], max_length=16)),
                ('previous_status', models.CharField(blank=True, max_length=16)),
                ('previous_value', models.CharField(blank=True, max_length=255)),
                ('new_status', models.CharField(blank=True, max_length=16)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_permission_history', to='students.studentprofile')),
            ],
            options={
                'verbose_name_plural': 'leave permission history',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='leave_permi_student_706199_idx')],
            },
        ),
    ]
