# Generated by Django 5.2.6 on 2026-09-03 12:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_permissions', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavepermissionhistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leavepermissionhistory',
            name='student',
        ),
        migrations.CreateModel(
            name='PassRuleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_eligibility', models.CharField(blank=True, max_length=16)),
                ('previous_note', models.CharField(blank=True, max_length=255)),
                ('new_eligibility', models.CharField(blank=True, max_length=16)),
                ('new_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pass_rule_history', to='students.studentprofile')),
            ],
            options={
                'verbose_name_plural': 'pass rule history',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StudentPassRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligibility', models.CharField(choices=[('allowed', 'Kaphat kimenőt'), ('teacher_only', 'Csak a saját nevelőtanára adhat'), ('denied', 'Nem kaphat kimenőt'), ('other', 'Egyéb (lásd megjegyzés)')], default='allowed', max_length=16)),
                ('note', models.CharField(blank=True, help_text='Kötelező, ha az „Egyéb” beállítás van kiválasztva.', max_length=255)),
                ('set_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pass_rule', to='students.studentprofile')),
            ],
            options={
                'ordering': ['student__full_name'],
            },
        ),
        migrations.DeleteModel(
            name='LeavePermission',
        ),
        migrations.DeleteModel(
            name='LeavePermissionHistory',
        ),
        migrations.AddIndex(
            model_name='passrulehistory',
            index=models.Index(fields=['student', '-created_at'], name='leave_permi_student_7f8d90_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpassrule',
            index=models.Index(fields=['eligibility'], name='leave_permi_eligibi_f1bd69_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentpassrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('eligibility', 'other'), _negated=True), models.Q(('note', ''), _negated=True), _connector='OR'), name='passrule_other_requires_note'),
        ),
    ]
