# Generated by Django 5.2.6 on 2026-09-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_permissions', '0002_remove_leavepermissionhistory_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passrulehistory',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'kimenő jogosultság előzmény', 'verbose_name_plural': 'kimenő jogosultság előzmények'},
        ),
        migrations.AlterModelOptions(
            name='studentpassrule',
            options={'ordering': ['student__full_name'], 'verbose_name': 'kimenő jogosultság', 'verbose_name_plural': 'kimenő jogosultságok'},
        ),
        migrations.AlterField(
            model_name='studentpassrule',
            name='eligibility',
            field=models.CharField(choices=[('allowed', 'Kaphat kimenőt'), ('teacher_only', 'Csak a saját nevelőtanára adhat'), ('denied', 'Nem kaphat kimenőt'), ('other', 'Egyéb (lásd megjegyzés)')], default='allowed', max_length=16, verbose_name='beállítás'),
        ),
        migrations.AlterField(
            model_name='studentpassrule',
            name='note',
            field=models.CharField(blank=True, help_text='Kötelező, ha az „Egyéb” beállítás van kiválasztva.', max_length=255, verbose_name='megjegyzés'),
        ),
    ]
