# Generated by Django 5.2.6 on 2026-09-01 19:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('short_label', models.CharField(blank=True, max_length=16)),
                ('color', models.CharField(default='#64748b', max_length=16)),
                ('counts_as_inside', models.BooleanField(default=False)),
                ('student_selectable', models.BooleanField(default=True)),
                ('requires_note', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='statustype_single_default')],
            },
        ),
        migrations.CreateModel(
            name='PresenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('student', 'Diák'), ('teacher', 'Nevelőtanár'), ('porter', 'Portás'), ('admin', 'Adminisztrátor'), ('evening_check', 'Esti ellenőrzés'), ('morning_check', 'Reggeli ellenőrzés'), ('room_check', 'Szobaellenőrzés'), ('weekend_check', 'Hétvégi ellenőrzés'), ('import', 'Importálás'), ('system', 'Rendszer')], max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_presence_events', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presence_events', to='students.studentprofile')),
                ('new_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='presence.statustype')),
                ('old_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='presence.statustype')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='presence_pr_student_5a3a3a_idx'), models.Index(fields=['-created_at'], name='presence_pr_created_e18d67_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('student', 'Diák'), ('teacher', 'Nevelőtanár'), ('porter', 'Portás'), ('admin', 'Adminisztrátor'), ('evening_check', 'Esti ellenőrzés'), ('morning_check', 'Reggeli ellenőrzés'), ('room_check', 'Szobaellenőrzés'), ('weekend_check', 'Hétvégi ellenőrzés'), ('import', 'Importálás'), ('system', 'Rendszer')], default='system', max_length=32)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return_at', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_changes', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='presence.statustype')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to='students.studentprofile')),
            ],
            options={
                'ordering': ['student__full_name'],
                'indexes': [models.Index(fields=['status', 'changed_at'], name='presence_st_status__19e2fc_idx')],
            },
        ),
    ]
