# Generated by Django 5.2.6 on 2026-09-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statustype',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'státusz', 'verbose_name_plural': 'státuszok'},
        ),
        migrations.AlterField(
            model_name='presenceevent',
            name='source',
            field=models.CharField(choices=[('student', 'Diák'), ('teacher', 'Nevelőtanár'), ('porter', 'Portás'), ('admin', 'Adminisztrátor'), ('evening_check', 'Esti ellenőrzés'), ('morning_check', 'Reggeli ellenőrzés (régi)'), ('room_check', 'Szobaellenőrzés'), ('weekend_check', 'Hétvégi ellenőrzés'), ('import', 'Importálás'), ('system', 'Rendszer')], max_length=32),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='code',
            field=models.SlugField(max_length=32, unique=True, verbose_name='kód'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='color',
            field=models.CharField(default='#64748b', max_length=16, verbose_name='szín'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='counts_as_inside',
            field=models.BooleanField(default=False, verbose_name='bentlévőnek számít'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='aktív'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='alapértelmezett'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='label',
            field=models.CharField(max_length=64, verbose_name='megnevezés'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='requires_note',
            field=models.BooleanField(default=False, verbose_name='megjegyzés kötelező'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='short_label',
            field=models.CharField(blank=True, max_length=16, verbose_name='rövidítés'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='sorrend'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='student_selectable',
            field=models.BooleanField(default=True, verbose_name='diák választhatja'),
        ),
        migrations.AlterField(
            model_name='studentpresence',
            name='source',
            field=models.CharField(choices=[('student', 'Diák'), ('teacher', 'Nevelőtanár'), ('porter', 'Portás'), ('admin', 'Adminisztrátor'), ('evening_check', 'Esti ellenőrzés'), ('morning_check', 'Reggeli ellenőrzés (régi)'), ('room_check', 'Szobaellenőrzés'), ('weekend_check', 'Hétvégi ellenőrzés'), ('import', 'Importálás'), ('system', 'Rendszer')], default='system', max_length=32),
        ),
    ]
