# Generated by Django 5.2.6 on 2026-09-01 19:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=16, unique=True)),
                ('floor', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['floor', 'number'],
                'indexes': [models.Index(fields=['floor'], name='rooms_room_floor_e5a342_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='room_capacity_positive')],
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_room_assignments', to=settings.AUTH_USER_MODEL)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_room_assignments', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='rooms.room')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_assignments', to='core.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_assignments', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['student', 'is_active'], name='rooms_rooma_student_c0c1ff_idx'), models.Index(fields=['room', 'is_active'], name='rooms_rooma_room_id_ab40cd_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student',), name='roomassignment_one_active_per_student'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='roomassignment_end_after_start'), models.CheckConstraint(condition=models.Q(('is_active', False), ('end_date__isnull', True), _connector='OR'), name='roomassignment_active_has_no_end_date')],
            },
        ),
    ]
