# Generated by Django 5.2.6 on 2026-09-03 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['floor', 'number'], 'verbose_name': 'szoba', 'verbose_name_plural': 'szobák'},
        ),
        migrations.AlterModelOptions(
            name='roomassignment',
            options={'ordering': ['-start_date', '-id'], 'verbose_name': 'szobabeosztás', 'verbose_name_plural': 'szobabeosztások'},
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='férőhely'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveSmallIntegerField(verbose_name='emelet'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='aktív'),
        ),
        migrations.AlterField(
            model_name='room',
            name='notes',
            field=models.TextField(blank=True, verbose_name='megjegyzés'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=16, unique=True, verbose_name='szobaszám'),
        ),
        migrations.AlterField(
            model_name='roomassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='vége'),
        ),
        migrations.AlterField(
            model_name='roomassignment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='aktív'),
        ),
        migrations.AlterField(
            model_name='roomassignment',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='megjegyzés'),
        ),
        migrations.AlterField(
            model_name='roomassignment',
            name='start_date',
            field=models.DateField(verbose_name='kezdet'),
        ),
    ]
