# Generated by Django 5.2.6 on 2026-09-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmodule',
            name='key',
            field=models.CharField(choices=[('evening_check', 'Esti ellenőrzés'), ('room_checks', 'Reggeli és szobaellenőrzés'), ('weekend_stay', 'Hétvégi bennmaradás'), ('pass_rules', 'Kimenő jogosultság')], max_length=64, unique=True),
        ),
    ]
