# Generated by Django 5.2.6 on 2026-09-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_retire_modules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'ordering': ['-start_date'], 'verbose_name': 'tanév', 'verbose_name_plural': 'tanévek'},
        ),
        migrations.AlterModelOptions(
            name='systemmodule',
            options={'ordering': ['name'], 'verbose_name': 'modul', 'verbose_name_plural': 'modulok'},
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='end_date',
            field=models.DateField(verbose_name='vége'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='aktív'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='megnevezés'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='start_date',
            field=models.DateField(verbose_name='kezdet'),
        ),
        migrations.AlterField(
            model_name='systemmodule',
            name='description',
            field=models.TextField(blank=True, verbose_name='leírás'),
        ),
        migrations.AlterField(
            model_name='systemmodule',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='bekapcsolva'),
        ),
        migrations.AlterField(
            model_name='systemmodule',
            name='key',
            field=models.CharField(choices=[('evening_check', 'Esti ellenőrzés'), ('room_checks', 'Reggeli és szobaellenőrzés'), ('weekend_stay', 'Hétvégi bennmaradás'), ('pass_rules', 'Kimenő jogosultság')], max_length=64, unique=True, verbose_name='kulcs'),
        ),
        migrations.AlterField(
            model_name='systemmodule',
            name='name',
            field=models.CharField(max_length=128, verbose_name='megnevezés'),
        ),
    ]
