# Generated by Django 5.2.6 on 2026-09-01 19:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('normal', 'Tanítási nap'), ('weekend', 'Hétvége'), ('holiday', 'Ünnepnap'), ('break', 'Szünet'), ('closed', 'Kollégium zárva')], default='normal', max_length=16)),
                ('evening_check_required', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_days', to='core.schoolyear')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='dormcalenda_date_1ba82e_idx'), models.Index(fields=['school_year', 'date'], name='dormcalenda_school__10935f_idx')],
            },
        ),
    ]
