# Generated by Django 5.2.6 on 2026-09-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarday',
            options={'ordering': ['-date'], 'verbose_name': 'naptári nap', 'verbose_name_plural': 'naptári napok'},
        ),
        migrations.AlterField(
            model_name='calendarday',
            name='date',
            field=models.DateField(unique=True, verbose_name='dátum'),
        ),
        migrations.AlterField(
            model_name='calendarday',
            name='evening_check_required',
            field=models.BooleanField(default=True, verbose_name='esti ellenőrzés kell'),
        ),
        migrations.AlterField(
            model_name='calendarday',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='megjegyzés'),
        ),
        migrations.AlterField(
            model_name='calendarday',
            name='status',
            field=models.CharField(choices=[('normal', 'Tanítási nap'), ('weekend', 'Hétvége'), ('holiday', 'Ünnepnap'), ('break', 'Szünet'), ('closed', 'Kollégium zárva')], default='normal', max_length=16, verbose_name='nap típusa'),
        ),
    ]
