# Generated by Django 5.2.6 on 2026-09-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name', 'username'], 'verbose_name': 'felhasználó', 'verbose_name_plural': 'felhasználók'},
        ),
        migrations.AlterField(
            model_name='user',
            name='extra_capabilities',
            field=models.JSONField(blank=True, default=list, verbose_name='többletjogosultságok'),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='jelszócsere kötelező'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='jelszó módosítva'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='telefonszám'),
        ),
        migrations.AlterField(
            model_name='user',
            name='revoked_capabilities',
            field=models.JSONField(blank=True, default=list, verbose_name='visszavont jogosultságok'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Adminisztrátor'), ('management', 'Vezetőség'), ('teacher', 'Nevelőtanár'), ('porter', 'Portás'), ('student', 'Diák')], default='student', max_length=32, verbose_name='szerepkör'),
        ),
    ]
