# Generated by Django 5.2.6 on 2026-09-01 19:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekendCheckSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('open', 'Nyitva'), ('closed', 'Lezárva')], default='open', max_length=16)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.CharField(blank=True, max_length=255)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('weekend_start', models.DateField()),
                ('check_type', models.CharField(choices=[('friday_evening', 'Péntek este'), ('saturday_morning', 'Szombat reggel'), ('saturday_evening', 'Szombat este'), ('sunday_morning', 'Vasárnap reggel')], max_length=32)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-weekend_start', 'check_type'],
            },
        ),
        migrations.CreateModel(
            name='WeekendStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekend_start', models.DateField(help_text='The Friday the weekend starts on.')),
                ('is_guest', models.BooleanField(default=False)),
                ('guest_name', models.CharField(blank=True, max_length=200)),
                ('guest_phone', models.CharField(blank=True, max_length=32)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_guardian_name', models.CharField(blank=True, max_length=200)),
                ('guest_guardian_phone', models.CharField(blank=True, max_length=32)),
                ('guest_guardian_email', models.EmailField(blank=True, max_length=254)),
                ('room_number', models.CharField(blank=True, max_length=16)),
                ('group_name', models.CharField(blank=True, max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('friday_stay', models.BooleanField(default=False)),
                ('saturday_stay', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Elbírálásra vár'), ('approved', 'Jóváhagyva'), ('rejected', 'Elutasítva'), ('cancelled', 'Visszavonva')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekend_stays', to='rooms.room')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekend_stays', to='students.studentprofile')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['room_number', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='WeekendCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(choices=[('inside', 'Bent'), ('outside', 'Kint'), ('pending', 'Nem ellenőrzött')], default='pending', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='weekend.weekendchecksession')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='weekend.weekendstay')),
            ],
            options={
                'ordering': ['stay__room_number', 'stay__display_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='weekendchecksession',
            constraint=models.UniqueConstraint(fields=('weekend_start', 'check_type'), name='weekendsession_unique_weekend_type'),
        ),
        migrations.AddIndex(
            model_name='weekendstay',
            index=models.Index(fields=['weekend_start', 'status'], name='weekend_wee_weekend_4e0da3_idx'),
        ),
        migrations.AddConstraint(
            model_name='weekendstay',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('student', 'weekend_start'), name='weekendstay_one_per_student_per_weekend'),
        ),
        migrations.AddConstraint(
            model_name='weekendstay',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_guest', True), ('student__isnull', True)), models.Q(('is_guest', False), ('student__isnull', False)), _connector='OR'), name='weekendstay_guest_xor_student'),
        ),
        migrations.AddConstraint(
            model_name='weekendstay',
            constraint=models.CheckConstraint(condition=models.Q(('friday_stay', True), ('saturday_stay', True), _connector='OR'), name='weekendstay_at_least_one_night'),
        ),
        migrations.AddConstraint(
            model_name='weekendcheck',
            constraint=models.UniqueConstraint(fields=('session', 'stay'), name='weekendcheck_unique_session_stay'),
        ),
    ]
