# Generated by Django 5.2.6 on 2026-09-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekendchecksession',
            name='check_type',
            field=models.CharField(choices=[('friday_evening', 'Péntek éjszaka'), ('saturday_evening', 'Szombat éjszaka')], max_length=32),
        ),
    ]
