# Generated by Django 5.2.6 on 2026-09-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekend', '0003_drop_weekend_morning_checks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekendstay',
            options={'ordering': ['room_number', 'display_name'], 'verbose_name': 'hétvégi bennmaradás', 'verbose_name_plural': 'hétvégi bennmaradások'},
        ),
        migrations.AlterField(
            model_name='weekendstay',
            name='friday_stay',
            field=models.BooleanField(default=False, verbose_name='péntek éjszaka'),
        ),
        migrations.AlterField(
            model_name='weekendstay',
            name='note',
            field=models.TextField(blank=True, verbose_name='megjegyzés'),
        ),
        migrations.AlterField(
            model_name='weekendstay',
            name='saturday_stay',
            field=models.BooleanField(default=False, verbose_name='szombat éjszaka'),
        ),
    ]
