# Generated by Django 5.2.6 on 2026-09-01 19:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('education_id', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='oktatási azonosító')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('school_class', models.CharField(blank=True, max_length=32)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_phone', models.CharField(blank=True, max_length=32)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32)),
                ('medical_notes', models.TextField(blank=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_students', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='people.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_changes', models.JSONField(default=dict)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Elbírálásra vár'), ('approved', 'Jóváhagyva'), ('rejected', 'Elutasítva'), ('withdrawn', 'Visszavonva')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_change_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['is_active'], name='students_st_is_acti_f5bb3f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['group', 'is_active'], name='students_st_group_i_7e37b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('move_out_date__isnull', True), ('move_in_date__isnull', True), ('move_out_date__gte', models.F('move_in_date')), _connector='OR'), name='student_move_out_after_move_in'),
        ),
        migrations.AddIndex(
            model_name='studentchangerequest',
            index=models.Index(fields=['status', '-created_at'], name='students_st_status_0267f1_idx'),
        ),
    ]
