# Generated by Django 5.2.6 on 2026-09-03 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_group_options_alter_teacher_options_and_more'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['full_name'], 'verbose_name': 'diák', 'verbose_name_plural': 'diákok'},
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='lakcím'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='archiválva'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='születési dátum'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='vészhelyzeti kapcsolattartó'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='vészhelyzeti telefonszám'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='teljes név'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='people.group', verbose_name='csoport'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='gondviselő e-mail címe'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='gondviselő neve'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='gondviselő telefonszáma'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='aktív'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='medical_notes',
            field=models.TextField(blank=True, verbose_name='egészségügyi megjegyzés'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='move_in_date',
            field=models.DateField(blank=True, null=True, verbose_name='beköltözés'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='move_out_date',
            field=models.DateField(blank=True, null=True, verbose_name='kiköltözés'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='telefonszám'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school_class',
            field=models.CharField(blank=True, max_length=32, verbose_name='osztály'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='iskola'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='staff_notes',
            field=models.TextField(blank=True, verbose_name='nevelői megjegyzés'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='felhasználó'),
        ),
    ]
