# Generated by Django 5.2.6 on 2026-09-03 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['code'], 'verbose_name': 'csoport', 'verbose_name_plural': 'csoportok'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['full_name'], 'verbose_name': 'nevelőtanár', 'verbose_name_plural': 'nevelőtanárok'},
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='kód'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, verbose_name='leírás'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='aktív'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=128, verbose_name='név'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='can_manage_all_weekend_stays',
            field=models.BooleanField(default=False, verbose_name='teljes hétvégi jogosultság'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='teljes név'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='people.group', verbose_name='további csoportok'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='has_all_student_access',
            field=models.BooleanField(default=False, verbose_name='minden diákhoz hozzáfér'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='aktív'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='telefonszám'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='primary_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_teachers', to='people.group', verbose_name='elsődleges csoport'),
        ),
    ]
